from pydantic_settings import BaseSettings
from typing import List


class Settings(BaseSettings):
    # Database
    DATABASE_URL: str = "postgresql://tbs_user:tbs_secure_2024@localhost:5432/tbs_marketing"
    
    # Google OAuth
    GOOGLE_CLIENT_ID: str
    GOOGLE_CLIENT_SECRET: str

    # Google Ads API (optional — requires a Google-approved developer token).
    # When GOOGLE_ADS_DEVELOPER_TOKEN is empty the Ads integration reports
    # "not configured" instead of erroring, so the app still boots and works.
    GOOGLE_ADS_DEVELOPER_TOKEN: str = ""
    GOOGLE_ADS_LOGIN_CUSTOMER_ID: str = ""  # optional MCC id, digits only, no dashes
    
    # JWT
    SECRET_KEY: str
    ALGORITHM: str = "HS256"
    ACCESS_TOKEN_EXPIRE_MINUTES: int = 60 * 24 * 7  # 7 days
    
    # API Keys (Optional)
    OPENAI_API_KEY: str = ""
    # AI-deck photos are generated by Supermachine (dev.supermachine.art).
    SUPERMACHINE_API_KEY: str = ""
    SUPERMACHINE_MODEL: str = "Supermachine NextGen"
    ANTHROPIC_API_KEY: str = ""
    GROQ_API_KEY: str = ""
    DEEPSEEK_API_KEY: str = ""
    SERPAPI_KEY: str = ""
    FIRECRAWL_API_KEY: str = ""
    SERANKING_API_KEY: str = ""  # SE Ranking Project API — TBS's account key (API > Dashboard)
    # PageSpeed Insights (technical audit Core Web Vitals). Keyless works at very
    # low volume but is quickly rate-limited (429); set a free key for reliability.
    PAGESPEED_API_KEY: str = ""

    # Additional provider keys (optional)
    QWEN_API_KEY: str = ""        # Alibaba Qwen
    KIMI_API_KEY: str = ""        # Moonshot Kimi
    BYTEDANCE_API_KEY: str = ""   # ByteDance / Doubao
    REPLICATE_API_KEY: str = ""   # Replicate
    XAI_API_KEY: str = ""         # xAI (Grok)
    MINIMAX_API_KEY: str = ""     # MiniMax
    PEXELS_API_KEY: str = ""      # Pexels stock images
    PIXABAY_API_KEY: str = ""     # Pixabay stock images
    
    # App Settings
    ENVIRONMENT: str = "development"
    ALLOWED_ORIGINS: str = (
        "http://localhost:5173,http://localhost:3000,"
        "https://analysis.phyominthein.com,https://analysis.phyominthein.com/,"
        "https://api.phyominthein.com,https://api.phyominthein.com/"
    )
    
    @property
    def allowed_origins_list(self) -> List[str]:
        return [origin.strip() for origin in self.ALLOWED_ORIGINS.split(",")]
    
    class Config:
        env_file = ".env"
        case_sensitive = True


settings = Settings()
