from pydantic_settings import BaseSettings
from typing import List


class Settings(BaseSettings):
    # Database
    DATABASE_URL: str = "postgresql://tbs_user:tbs_secure_2024@localhost:5432/tbs_marketing"
    
    # Google OAuth
    GOOGLE_CLIENT_ID: str
    GOOGLE_CLIENT_SECRET: str

    # Bing Webmaster Tools OAuth (optional). Registered in BWT → Settings → API Access →
    # OAuth Client. When id/secret are empty the Bing integration reports
    # "not configured" instead of erroring, so the app still boots and works.
    BING_CLIENT_ID: str = ""
    BING_CLIENT_SECRET: str = ""
    # Default redirect URI (dev). The frontend passes its own origin-based URI at runtime,
    # so this is only a fallback; the value used must be registered on the BWT OAuth client.
    BING_REDIRECT_URI: str = "http://localhost:5173/bing-callback"

    # Google Ads API (optional — requires a Google-approved developer token).
    # When GOOGLE_ADS_DEVELOPER_TOKEN is empty the Ads integration reports
    # "not configured" instead of erroring, so the app still boots and works.
    GOOGLE_ADS_DEVELOPER_TOKEN: str = ""
    GOOGLE_ADS_LOGIN_CUSTOMER_ID: str = ""  # optional MCC id, digits only, no dashes
    
    # JWT
    SECRET_KEY: str
    ALGORITHM: str = "HS256"
    ACCESS_TOKEN_EXPIRE_MINUTES: int = 60 * 24 * 7  # 7 days
    
    # API Keys (Optional)
    OPENAI_API_KEY: str = ""
    # Model id for the OpenAI Responses-API provider. Overridable in .env so a newer id can be
    # swapped in without a deploy; the provider is hidden from the picker unless OPENAI_API_KEY
    # is also set.
    OPENAI_RESPONSES_MODEL: str = "gpt-5.6-luna"
    # gpt-5.6-luna is a REASONING model and defaults to medium effort. Reasoning tokens are billed
    # and count against max_output_tokens, so on a long writing task like a deck a high effort can
    # consume the whole budget and return no HTML at all — the exact failure GLM-5.2 hit here
    # (410s, 53K reasoning chars, zero content). Low keeps some planning without that risk.
    # Values: none | low | medium | high | xhigh | max.
    OPENAI_REASONING_EFFORT: str = "low"
    # AI-deck photos are generated by Supermachine (dev.supermachine.art).
    SUPERMACHINE_API_KEY: str = ""
    SUPERMACHINE_MODEL: str = "Supermachine NextGen"
    ANTHROPIC_API_KEY: str = ""
    GROQ_API_KEY: str = ""
    DEEPSEEK_API_KEY: str = ""
    SERPAPI_KEY: str = ""
    FIRECRAWL_API_KEY: str = ""
    MANGOOLS_API_KEY: str = ""   # KWFinder REST API (x-access-token) — real keyword volume + KD
    SERPAPI_MONTHLY_CAP: int = 0  # optional spend ceiling: block SERP jobs past this month's usage (0 = off)
    # Resolve AI Overview citations. Google returns the AI Overview as a page_token, so reading who
    # it cites needs a SECOND SerpAPI call — doubling cost on affected keywords. Off by default.
    AI_OVERVIEW_DETAIL: str = "0"
    # Verify that AI-invented topical-map nodes are genuinely distinct pages by comparing their
    # SERPs, merging any that Google answers with the same URLs. Costs one cached SerpAPI search
    # per node checked, once per analysis. Set to "0" to skip and trust the prompt instead.
    NODE_SERP_VALIDATION: str = "1"
    # PageSpeed Insights (technical audit Core Web Vitals). Keyless works at very
    # low volume but is quickly rate-limited (429); set a free key for reliability.
    PAGESPEED_API_KEY: str = ""

    # Additional provider keys (optional)
    QWEN_API_KEY: str = ""        # Alibaba Token Plan seat key (sk-sp-…) — powers Qwen, GLM-5.2,
                                  # DeepSeek V4 Pro and Kimi via the plan's dedicated base URL.
                                  # NOT a public DashScope pay-as-you-go key (those bill per token).
    KIMI_API_KEY: str = ""        # Moonshot Kimi
    BYTEDANCE_API_KEY: str = ""   # ByteDance / Doubao
    REPLICATE_API_KEY: str = ""   # Replicate
    XAI_API_KEY: str = ""         # xAI (Grok)
    MINIMAX_API_KEY: str = ""     # MiniMax
    # MiniMax OpenAI-compatible endpoint + model, used by the in-app AI assistant.
    # Region differs per account (global api.minimax.io vs china api.minimax.chat).
    MINIMAX_BASE_URL: str = "https://api.minimax.io/v1"
    MINIMAX_MODEL: str = "MiniMax-M1"
    PEXELS_API_KEY: str = ""      # Pexels stock images
    PIXABAY_API_KEY: str = ""     # Pixabay stock images
    
    # App Settings
    ENVIRONMENT: str = "development"
    ALLOWED_ORIGINS: str = (
        "http://localhost:5173,http://localhost:3000,"
        "https://tool.tbs-dev.com,https://tool.tbs-dev.com/"
    )
    
    @property
    def allowed_origins_list(self) -> List[str]:
        return [origin.strip() for origin in self.ALLOWED_ORIGINS.split(",")]
    
    class Config:
        env_file = ".env"
        case_sensitive = True


settings = Settings()
